services:

#  stats-server:
#    build: gateway
#    image: shareit-gateway
#    restart: on-failure
#    container_name: shareit-gateway
#    ports:
#      - "9090:9090"

#  stats-db:
#    image: postgres:16.1
#
#  ewm-service:
#    ports:
#      - "8080:8080"
#
#  ewm-db:
#    image: postgres:16.1

  db-stat:
    image: postgres:alpine
    ports:
      - "5432:5432"
    volumes:
      - ./stat-postgres:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=stat_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10