#services:

#  stats-server:
#    build: gateway
#    image: shareit-gateway
#    restart: on-failure
#    container_name: shareit-gateway
#    ports:
#      - "9090:9090"

#  stats-db:
#    image: postgres:16.1
#
#  ewm-service:
#    ports:
#      - "8080:8080"
#
#  ewm-db:
#    image: postgres:16.1
