services:

  stats-server:
    build: stat/stat-server
    image: stat-server
    container_name: stat-server
    restart: on-failure
    ports:
      - "9090:9090"
    depends_on:
      - db-stat
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-stat:5432/stat_db

  db-stat:
    image: postgres:alpine
    container_name: db-stat
    ports:
      - "5432:5432"
    volumes:
      - ./stat-postgres:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=stat_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10
