
CREATE TABLE IF NOT EXISTS users (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    VARCHAR(254) NOT NULL UNIQUE,
    name     VARCHAR(250) NOT NULL
);


-- эту строчку надо удалить, она только для того чтобы работал внешний ключ в requests
CREATE TABLE IF NOT EXISTS events ( id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY );


CREATE TABLE IF NOT EXISTS requests (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requester_id    BIGINT NOT NULL REFERENCES users(id)    ON DELETE CASCADE   ON UPDATE RESTRICT,
    event_id        BIGINT NOT NULL REFERENCES events(id)   ON DELETE CASCADE   ON UPDATE RESTRICT,
    status          VARCHAR(15) NOT NULL,
    created_at      TIMESTAMP NOT NULL
);

