
CREATE TABLE IF NOT EXISTS users (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    VARCHAR(254) NOT NULL UNIQUE,
    name     VARCHAR(250) NOT NULL
);

CREATE TABLE IF NOT EXISTS compilations (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pinned  BOOLEAN       NOT NULL,
    title   VARCHAR(200)  NOT NULL,
);

CREATE TABLE IF NOT EXISTS compilations_events (
    compilations_id BIGINT  NOT NULL,
    events_id       BIGINT  NOT NULL,

    CONSTRAINT pk_compilations_events PRIMARY KEY (compilations_id, events_id),
    CONSTRAINT fk_compilations FOREIGN KEY (compilations_id) REFERENCES compilations (id) ON DELETE CASCADE,
    CONSTRAINT fk_events FOREIGN KEY (events_id) REFERENCES event (id) ON DELETE CASCADE
);

-- эту строчку надо удалить, она только для того чтобы работал внешний ключ в requests
CREATE TABLE IF NOT EXISTS events ( id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY );


CREATE TABLE IF NOT EXISTS requests (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requester_id    BIGINT NOT NULL REFERENCES users(id)    ON DELETE CASCADE   ON UPDATE RESTRICT,
    event_id        BIGINT NOT NULL REFERENCES events(id)   ON DELETE CASCADE   ON UPDATE RESTRICT,
    status          VARCHAR(15) NOT NULL,
    created_at      TIMESTAMP NOT NULL
);

